//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using TCESS.ESales.PersistenceLayer.Entity;

namespace TCESS.ESales.PersistenceLayer.EF
{
    public partial class eSalesEntities : ObjectContext
    {
        public const string ConnectionString = "name=eSalesEntities";
        public const string ContainerName = "eSalesEntities";
    
        #region Constructors
    
        public eSalesEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public eSalesEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public eSalesEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<affidavitdetail> affidavitdetails
        {
            get { return _affidavitdetails  ?? (_affidavitdetails = CreateObjectSet<affidavitdetail>("affidavitdetails")); }
        }
        private ObjectSet<affidavitdetail> _affidavitdetails;
    
        public ObjectSet<agentdetail> agentdetails
        {
            get { return _agentdetails  ?? (_agentdetails = CreateObjectSet<agentdetail>("agentdetails")); }
        }
        private ObjectSet<agentdetail> _agentdetails;
    
        public ObjectSet<agentmaterialpercentage> agentmaterialpercentages
        {
            get { return _agentmaterialpercentages  ?? (_agentmaterialpercentages = CreateObjectSet<agentmaterialpercentage>("agentmaterialpercentages")); }
        }
        private ObjectSet<agentmaterialpercentage> _agentmaterialpercentages;
    
        public ObjectSet<allotedquantity> allotedquantities
        {
            get { return _allotedquantities  ?? (_allotedquantities = CreateObjectSet<allotedquantity>("allotedquantities")); }
        }
        private ObjectSet<allotedquantity> _allotedquantities;
    
        public ObjectSet<ameblock> ameblocks
        {
            get { return _ameblocks  ?? (_ameblocks = CreateObjectSet<ameblock>("ameblocks")); }
        }
        private ObjectSet<ameblock> _ameblocks;
    
        public ObjectSet<authrepdetail> authrepdetails
        {
            get { return _authrepdetails  ?? (_authrepdetails = CreateObjectSet<authrepdetail>("authrepdetails")); }
        }
        private ObjectSet<authrepdetail> _authrepdetails;
    
        public ObjectSet<authrepdocdetail> authrepdocdetails
        {
            get { return _authrepdocdetails  ?? (_authrepdocdetails = CreateObjectSet<authrepdocdetail>("authrepdocdetails")); }
        }
        private ObjectSet<authrepdocdetail> _authrepdocdetails;
    
        public ObjectSet<authrepdocument> authrepdocuments
        {
            get { return _authrepdocuments  ?? (_authrepdocuments = CreateObjectSet<authrepdocument>("authrepdocuments")); }
        }
        private ObjectSet<authrepdocument> _authrepdocuments;
    
        public ObjectSet<bank> banks
        {
            get { return _banks  ?? (_banks = CreateObjectSet<bank>("banks")); }
        }
        private ObjectSet<bank> _banks;
    
        public ObjectSet<bookingmode> bookingmodes
        {
            get { return _bookingmodes  ?? (_bookingmodes = CreateObjectSet<bookingmode>("bookingmodes")); }
        }
        private ObjectSet<bookingmode> _bookingmodes;
    
        public ObjectSet<bookingmodedetail> bookingmodedetails
        {
            get { return _bookingmodedetails  ?? (_bookingmodedetails = CreateObjectSet<bookingmodedetail>("bookingmodedetails")); }
        }
        private ObjectSet<bookingmodedetail> _bookingmodedetails;
    
        public ObjectSet<businesstype> businesstypes
        {
            get { return _businesstypes  ?? (_businesstypes = CreateObjectSet<businesstype>("businesstypes")); }
        }
        private ObjectSet<businesstype> _businesstypes;
    
        public ObjectSet<counter> counters
        {
            get { return _counters  ?? (_counters = CreateObjectSet<counter>("counters")); }
        }
        private ObjectSet<counter> _counters;
    
        public ObjectSet<counterdetail> counterdetails
        {
            get { return _counterdetails  ?? (_counterdetails = CreateObjectSet<counterdetail>("counterdetails")); }
        }
        private ObjectSet<counterdetail> _counterdetails;
    
        public ObjectSet<custauthorizationdetail> custauthorizationdetails
        {
            get { return _custauthorizationdetails  ?? (_custauthorizationdetails = CreateObjectSet<custauthorizationdetail>("custauthorizationdetails")); }
        }
        private ObjectSet<custauthorizationdetail> _custauthorizationdetails;
    
        public ObjectSet<customer> customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<customer>("customers")); }
        }
        private ObjectSet<customer> _customers;
    
        public ObjectSet<customer_history> customer_history
        {
            get { return _customer_history  ?? (_customer_history = CreateObjectSet<customer_history>("customer_history")); }
        }
        private ObjectSet<customer_history> _customer_history;
    
        public ObjectSet<customerdocdetail> customerdocdetails
        {
            get { return _customerdocdetails  ?? (_customerdocdetails = CreateObjectSet<customerdocdetail>("customerdocdetails")); }
        }
        private ObjectSet<customerdocdetail> _customerdocdetails;
    
        public ObjectSet<customerdocument> customerdocuments
        {
            get { return _customerdocuments  ?? (_customerdocuments = CreateObjectSet<customerdocument>("customerdocuments")); }
        }
        private ObjectSet<customerdocument> _customerdocuments;
    
        public ObjectSet<customermaterialmap> customermaterialmaps
        {
            get { return _customermaterialmaps  ?? (_customermaterialmaps = CreateObjectSet<customermaterialmap>("customermaterialmaps")); }
        }
        private ObjectSet<customermaterialmap> _customermaterialmaps;
    
        public ObjectSet<customerpartner> customerpartners
        {
            get { return _customerpartners  ?? (_customerpartners = CreateObjectSet<customerpartner>("customerpartners")); }
        }
        private ObjectSet<customerpartner> _customerpartners;
    
        public ObjectSet<dcamaterialallocation> dcamaterialallocations
        {
            get { return _dcamaterialallocations  ?? (_dcamaterialallocations = CreateObjectSet<dcamaterialallocation>("dcamaterialallocations")); }
        }
        private ObjectSet<dcamaterialallocation> _dcamaterialallocations;
    
        public ObjectSet<district> districts
        {
            get { return _districts  ?? (_districts = CreateObjectSet<district>("districts")); }
        }
        private ObjectSet<district> _districts;
    
        public ObjectSet<doctype> doctypes
        {
            get { return _doctypes  ?? (_doctypes = CreateObjectSet<doctype>("doctypes")); }
        }
        private ObjectSet<doctype> _doctypes;
    
        public ObjectSet<form27c> form27c
        {
            get { return _form27c  ?? (_form27c = CreateObjectSet<form27c>("form27c")); }
        }
        private ObjectSet<form27c> _form27c;
    
        public ObjectSet<form27c_history> form27c_history
        {
            get { return _form27c_history  ?? (_form27c_history = CreateObjectSet<form27c_history>("form27c_history")); }
        }
        private ObjectSet<form27c_history> _form27c_history;
    
        public ObjectSet<form27cperiodtype> form27cperiodtype
        {
            get { return _form27cperiodtype  ?? (_form27cperiodtype = CreateObjectSet<form27cperiodtype>("form27cperiodtype")); }
        }
        private ObjectSet<form27cperiodtype> _form27cperiodtype;
    
        public ObjectSet<liftinginterval> liftingintervals
        {
            get { return _liftingintervals  ?? (_liftingintervals = CreateObjectSet<liftinginterval>("liftingintervals")); }
        }
        private ObjectSet<liftinginterval> _liftingintervals;
    
        public ObjectSet<liftinglimit> liftinglimits
        {
            get { return _liftinglimits  ?? (_liftinglimits = CreateObjectSet<liftinglimit>("liftinglimits")); }
        }
        private ObjectSet<liftinglimit> _liftinglimits;
    
        public ObjectSet<liftinglimit_history> liftinglimit_history
        {
            get { return _liftinglimit_history  ?? (_liftinglimit_history = CreateObjectSet<liftinglimit_history>("liftinglimit_history")); }
        }
        private ObjectSet<liftinglimit_history> _liftinglimit_history;
    
        public ObjectSet<materialtype> materialtypes
        {
            get { return _materialtypes  ?? (_materialtypes = CreateObjectSet<materialtype>("materialtypes")); }
        }
        private ObjectSet<materialtype> _materialtypes;
    
        public ObjectSet<materialtype_history> materialtype_history
        {
            get { return _materialtype_history  ?? (_materialtype_history = CreateObjectSet<materialtype_history>("materialtype_history")); }
        }
        private ObjectSet<materialtype_history> _materialtype_history;
    
        public ObjectSet<moneyreceipt> moneyreceipts
        {
            get { return _moneyreceipts  ?? (_moneyreceipts = CreateObjectSet<moneyreceipt>("moneyreceipts")); }
        }
        private ObjectSet<moneyreceipt> _moneyreceipts;
    
        public ObjectSet<month> months
        {
            get { return _months  ?? (_months = CreateObjectSet<month>("months")); }
        }
        private ObjectSet<month> _months;
    
        public ObjectSet<my_ameblocks> my_ameblocks
        {
            get { return _my_ameblocks  ?? (_my_ameblocks = CreateObjectSet<my_ameblocks>("my_ameblocks")); }
        }
        private ObjectSet<my_ameblocks> _my_ameblocks;
    
        public ObjectSet<my_aspnet_applications> my_aspnet_applications
        {
            get { return _my_aspnet_applications  ?? (_my_aspnet_applications = CreateObjectSet<my_aspnet_applications>("my_aspnet_applications")); }
        }
        private ObjectSet<my_aspnet_applications> _my_aspnet_applications;
    
        public ObjectSet<my_aspnet_membership> my_aspnet_membership
        {
            get { return _my_aspnet_membership  ?? (_my_aspnet_membership = CreateObjectSet<my_aspnet_membership>("my_aspnet_membership")); }
        }
        private ObjectSet<my_aspnet_membership> _my_aspnet_membership;
    
        public ObjectSet<my_aspnet_roles> my_aspnet_roles
        {
            get { return _my_aspnet_roles  ?? (_my_aspnet_roles = CreateObjectSet<my_aspnet_roles>("my_aspnet_roles")); }
        }
        private ObjectSet<my_aspnet_roles> _my_aspnet_roles;
    
        public ObjectSet<my_aspnet_users> my_aspnet_users
        {
            get { return _my_aspnet_users  ?? (_my_aspnet_users = CreateObjectSet<my_aspnet_users>("my_aspnet_users")); }
        }
        private ObjectSet<my_aspnet_users> _my_aspnet_users;
    
        public ObjectSet<my_aspnet_usersinroles> my_aspnet_usersinroles
        {
            get { return _my_aspnet_usersinroles  ?? (_my_aspnet_usersinroles = CreateObjectSet<my_aspnet_usersinroles>("my_aspnet_usersinroles")); }
        }
        private ObjectSet<my_aspnet_usersinroles> _my_aspnet_usersinroles;
    
        public ObjectSet<ownershipstatu> ownershipstatus
        {
            get { return _ownershipstatus  ?? (_ownershipstatus = CreateObjectSet<ownershipstatu>("ownershipstatus")); }
        }
        private ObjectSet<ownershipstatu> _ownershipstatus;
    
        public ObjectSet<pageinfo> pageinfoes
        {
            get { return _pageinfoes  ?? (_pageinfoes = CreateObjectSet<pageinfo>("pageinfoes")); }
        }
        private ObjectSet<pageinfo> _pageinfoes;
    
        public ObjectSet<pagesinrole> pagesinroles
        {
            get { return _pagesinroles  ?? (_pagesinroles = CreateObjectSet<pagesinrole>("pagesinroles")); }
        }
        private ObjectSet<pagesinrole> _pagesinroles;
    
        public ObjectSet<paymentcollection> paymentcollections
        {
            get { return _paymentcollections  ?? (_paymentcollections = CreateObjectSet<paymentcollection>("paymentcollections")); }
        }
        private ObjectSet<paymentcollection> _paymentcollections;
    
        public ObjectSet<paymentmode> paymentmodes
        {
            get { return _paymentmodes  ?? (_paymentmodes = CreateObjectSet<paymentmode>("paymentmodes")); }
        }
        private ObjectSet<paymentmode> _paymentmodes;
    
        public ObjectSet<paymenttransit> paymenttransits
        {
            get { return _paymenttransits  ?? (_paymenttransits = CreateObjectSet<paymenttransit>("paymenttransits")); }
        }
        private ObjectSet<paymenttransit> _paymenttransits;
    
        public ObjectSet<periodtype> periodtypes
        {
            get { return _periodtypes  ?? (_periodtypes = CreateObjectSet<periodtype>("periodtypes")); }
        }
        private ObjectSet<periodtype> _periodtypes;
    
        public ObjectSet<rejectionreason> rejectionreasons
        {
            get { return _rejectionreasons  ?? (_rejectionreasons = CreateObjectSet<rejectionreason>("rejectionreasons")); }
        }
        private ObjectSet<rejectionreason> _rejectionreasons;
    
        public ObjectSet<settlementofaccount> settlementofaccounts
        {
            get { return _settlementofaccounts  ?? (_settlementofaccounts = CreateObjectSet<settlementofaccount>("settlementofaccounts")); }
        }
        private ObjectSet<settlementofaccount> _settlementofaccounts;
    
        public ObjectSet<smsbookinglimit> smsbookinglimits
        {
            get { return _smsbookinglimits  ?? (_smsbookinglimits = CreateObjectSet<smsbookinglimit>("smsbookinglimits")); }
        }
        private ObjectSet<smsbookinglimit> _smsbookinglimits;
    
        public ObjectSet<smsexecutivelist> smsexecutivelists
        {
            get { return _smsexecutivelists  ?? (_smsexecutivelists = CreateObjectSet<smsexecutivelist>("smsexecutivelists")); }
        }
        private ObjectSet<smsexecutivelist> _smsexecutivelists;
    
        public ObjectSet<smspaymentregistration> smspaymentregistrations
        {
            get { return _smspaymentregistrations  ?? (_smspaymentregistrations = CreateObjectSet<smspaymentregistration>("smspaymentregistrations")); }
        }
        private ObjectSet<smspaymentregistration> _smspaymentregistrations;
    
        public ObjectSet<smsregistration> smsregistrations
        {
            get { return _smsregistrations  ?? (_smsregistrations = CreateObjectSet<smsregistration>("smsregistrations")); }
        }
        private ObjectSet<smsregistration> _smsregistrations;
    
        public ObjectSet<standalonetruckdocdetail> standalonetruckdocdetails
        {
            get { return _standalonetruckdocdetails  ?? (_standalonetruckdocdetails = CreateObjectSet<standalonetruckdocdetail>("standalonetruckdocdetails")); }
        }
        private ObjectSet<standalonetruckdocdetail> _standalonetruckdocdetails;
    
        public ObjectSet<standalonetruck> standalonetrucks
        {
            get { return _standalonetrucks  ?? (_standalonetrucks = CreateObjectSet<standalonetruck>("standalonetrucks")); }
        }
        private ObjectSet<standalonetruck> _standalonetrucks;
    
        public ObjectSet<state> states
        {
            get { return _states  ?? (_states = CreateObjectSet<state>("states")); }
        }
        private ObjectSet<state> _states;
    
        public ObjectSet<truckcarrycapacity> truckcarrycapacities
        {
            get { return _truckcarrycapacities  ?? (_truckcarrycapacities = CreateObjectSet<truckcarrycapacity>("truckcarrycapacities")); }
        }
        private ObjectSet<truckcarrycapacity> _truckcarrycapacities;
    
        public ObjectSet<truckdetail> truckdetails
        {
            get { return _truckdetails  ?? (_truckdetails = CreateObjectSet<truckdetail>("truckdetails")); }
        }
        private ObjectSet<truckdetail> _truckdetails;
    
        public ObjectSet<truckdocdetail> truckdocdetails
        {
            get { return _truckdocdetails  ?? (_truckdocdetails = CreateObjectSet<truckdocdetail>("truckdocdetails")); }
        }
        private ObjectSet<truckdocdetail> _truckdocdetails;
    
        public ObjectSet<truckdocument> truckdocuments
        {
            get { return _truckdocuments  ?? (_truckdocuments = CreateObjectSet<truckdocument>("truckdocuments")); }
        }
        private ObjectSet<truckdocument> _truckdocuments;
    
        public ObjectSet<truckmake> truckmakes
        {
            get { return _truckmakes  ?? (_truckmakes = CreateObjectSet<truckmake>("truckmakes")); }
        }
        private ObjectSet<truckmake> _truckmakes;
    
        public ObjectSet<truckregtype> truckregtypes
        {
            get { return _truckregtypes  ?? (_truckregtypes = CreateObjectSet<truckregtype>("truckregtypes")); }
        }
        private ObjectSet<truckregtype> _truckregtypes;
    
        public ObjectSet<truckwheeler> truckwheelers
        {
            get { return _truckwheelers  ?? (_truckwheelers = CreateObjectSet<truckwheeler>("truckwheelers")); }
        }
        private ObjectSet<truckwheeler> _truckwheelers;
    
        public ObjectSet<useragentmapping> useragentmappings
        {
            get { return _useragentmappings  ?? (_useragentmappings = CreateObjectSet<useragentmapping>("useragentmappings")); }
        }
        private ObjectSet<useragentmapping> _useragentmappings;
    
        public ObjectSet<userpaymentmodemapping> userpaymentmodemappings
        {
            get { return _userpaymentmodemappings  ?? (_userpaymentmodemappings = CreateObjectSet<userpaymentmodemapping>("userpaymentmodemappings")); }
        }
        private ObjectSet<userpaymentmodemapping> _userpaymentmodemappings;
    
        public ObjectSet<bookingandsettlement> bookingandsettlements
        {
            get { return _bookingandsettlements  ?? (_bookingandsettlements = CreateObjectSet<bookingandsettlement>("bookingandsettlements")); }
        }
        private ObjectSet<bookingandsettlement> _bookingandsettlements;
    
        public ObjectSet<customerdetailsforcodealloc> customerdetailsforcodeallocs
        {
            get { return _customerdetailsforcodeallocs  ?? (_customerdetailsforcodeallocs = CreateObjectSet<customerdetailsforcodealloc>("customerdetailsforcodeallocs")); }
        }
        private ObjectSet<customerdetailsforcodealloc> _customerdetailsforcodeallocs;
    
        public ObjectSet<customerdocumentsview> customerdocumentsviews
        {
            get { return _customerdocumentsviews  ?? (_customerdocumentsviews = CreateObjectSet<customerdocumentsview>("customerdocumentsviews")); }
        }
        private ObjectSet<customerdocumentsview> _customerdocumentsviews;
    
        public ObjectSet<dformreport> dformreports
        {
            get { return _dformreports  ?? (_dformreports = CreateObjectSet<dformreport>("dformreports")); }
        }
        private ObjectSet<dformreport> _dformreports;
    
        public ObjectSet<dispatchreport> dispatchreports
        {
            get { return _dispatchreports  ?? (_dispatchreports = CreateObjectSet<dispatchreport>("dispatchreports")); }
        }
        private ObjectSet<dispatchreport> _dispatchreports;
    
        public ObjectSet<form27cview> form27cview
        {
            get { return _form27cview  ?? (_form27cview = CreateObjectSet<form27cview>("form27cview")); }
        }
        private ObjectSet<form27cview> _form27cview;
    
        public ObjectSet<loadingadivcerpt> loadingadivcerpts
        {
            get { return _loadingadivcerpts  ?? (_loadingadivcerpts = CreateObjectSet<loadingadivcerpt>("loadingadivcerpts")); }
        }
        private ObjectSet<loadingadivcerpt> _loadingadivcerpts;
    
        public ObjectSet<pervioussettlement> pervioussettlements
        {
            get { return _pervioussettlements  ?? (_pervioussettlements = CreateObjectSet<pervioussettlement>("pervioussettlements")); }
        }
        private ObjectSet<pervioussettlement> _pervioussettlements;
    
        public ObjectSet<roadpermitreport> roadpermitreports
        {
            get { return _roadpermitreports  ?? (_roadpermitreports = CreateObjectSet<roadpermitreport>("roadpermitreports")); }
        }
        private ObjectSet<roadpermitreport> _roadpermitreports;
    
        public ObjectSet<truckverification> truckverifications
        {
            get { return _truckverifications  ?? (_truckverifications = CreateObjectSet<truckverification>("truckverifications")); }
        }
        private ObjectSet<truckverification> _truckverifications;
    
        public ObjectSet<vwchequepayment> vwchequepayments
        {
            get { return _vwchequepayments  ?? (_vwchequepayments = CreateObjectSet<vwchequepayment>("vwchequepayments")); }
        }
        private ObjectSet<vwchequepayment> _vwchequepayments;
    
        public ObjectSet<vwcollectionsummary> vwcollectionsummaries
        {
            get { return _vwcollectionsummaries  ?? (_vwcollectionsummaries = CreateObjectSet<vwcollectionsummary>("vwcollectionsummaries")); }
        }
        private ObjectSet<vwcollectionsummary> _vwcollectionsummaries;
    
        public ObjectSet<vwnonchequepayment> vwnonchequepayments
        {
            get { return _vwnonchequepayments  ?? (_vwnonchequepayments = CreateObjectSet<vwnonchequepayment>("vwnonchequepayments")); }
        }
        private ObjectSet<vwnonchequepayment> _vwnonchequepayments;
    
        public ObjectSet<paymentrefund> paymentrefunds
        {
            get { return _paymentrefunds  ?? (_paymentrefunds = CreateObjectSet<paymentrefund>("paymentrefunds")); }
        }
        private ObjectSet<paymentrefund> _paymentrefunds;
    
        public ObjectSet<batchtransfer> batchtransfers
        {
            get { return _batchtransfers  ?? (_batchtransfers = CreateObjectSet<batchtransfer>("batchtransfers")); }
        }
        private ObjectSet<batchtransfer> _batchtransfers;
    
        public ObjectSet<booking> bookings
        {
            get { return _bookings  ?? (_bookings = CreateObjectSet<booking>("bookings")); }
        }
        private ObjectSet<booking> _bookings;

        #endregion
    }
}
