//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCESS.ESales.CommonLayer.CommonLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCESS.ESales.CommonLayer.CommonLibrary.Labels-en", typeof(Labels_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ALLDCADATA {
            get {
                return ResourceManager.GetString("ALLDCADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Agent.
        /// </summary>
        internal static string SELECTAGENT {
            get {
                return ResourceManager.GetString("SELECTAGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bank.
        /// </summary>
        internal static string SELECTBANK {
            get {
                return ResourceManager.GetString("SELECTBANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string SELECTDISTRICT {
            get {
                return ResourceManager.GetString("SELECTDISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Quantity.
        /// </summary>
        internal static string SELECTQUANTITY {
            get {
                return ResourceManager.GetString("SELECTQUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rejection Reasons.
        /// </summary>
        internal static string SELECTREJECTIONREASON {
            get {
                return ResourceManager.GetString("SELECTREJECTIONREASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        internal static string SELECTSTATE {
            get {
                return ResourceManager.GetString("SELECTSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Truck Carry Capacity.
        /// </summary>
        internal static string SELECTTRUCKCARRYCAPACITY {
            get {
                return ResourceManager.GetString("SELECTTRUCKCARRYCAPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Truck Make.
        /// </summary>
        internal static string SELECTTRUCKMAKE {
            get {
                return ResourceManager.GetString("SELECTTRUCKMAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Truck Wheels.
        /// </summary>
        internal static string SELECTTRUCKWHEELS {
            get {
                return ResourceManager.GetString("SELECTTRUCKWHEELS", resourceCulture);
            }
        }
    }
}
