//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class affidavitdetail : EntityBase
    {
        #region Primitive Properties
    
        public virtual int AffidavitDetailsId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AffidavitSubmitDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AffidavitExpiryDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AffidavitCreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AffidavitCreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AffidavitIsSubmitted
        {
            get;
            set;
        }
    
        public virtual int Affidavit_CustID
        {
            get { return _affidavit_CustID; }
            set
            {
                if (_affidavit_CustID != value)
                {
                    if (customer != null && customer.Cust_Id != value)
                    {
                        customer = null;
                    }
                    _affidavit_CustID = value;
                }
            }
        }
        private int _affidavit_CustID;
    
        public virtual string Affidavit_ApprovedBy
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual customer customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    Fixupcustomer(previousValue);
                }
            }
        }
        private customer _customer;

        #endregion
        #region Association Fixup
    
        private void Fixupcustomer(customer previousValue)
        {
            if (previousValue != null && previousValue.affidavitdetails.Contains(this))
            {
                previousValue.affidavitdetails.Remove(this);
            }
    
            if (customer != null)
            {
                if (!customer.affidavitdetails.Contains(this))
                {
                    customer.affidavitdetails.Add(this);
                }
                if (Affidavit_CustID != customer.Cust_Id)
                {
                    Affidavit_CustID = customer.Cust_Id;
                }
            }
        }

        #endregion
    }
}
