//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class agentmaterialpercentage : EntityBase
    {
        #region Primitive Properties
    
        public virtual int AMP_Id
        {
            get;
            set;
        }
    
        public virtual int AMP_Agent_Id
        {
            get { return _aMP_Agent_Id; }
            set
            {
                if (_aMP_Agent_Id != value)
                {
                    if (agentdetail != null && agentdetail.Agent_Id != value)
                    {
                        agentdetail = null;
                    }
                    _aMP_Agent_Id = value;
                }
            }
        }
        private int _aMP_Agent_Id;
    
        public virtual int AMP_MaterialType_Id
        {
            get { return _aMP_MaterialType_Id; }
            set
            {
                if (_aMP_MaterialType_Id != value)
                {
                    if (materialtype != null && materialtype.MaterialType_Id != value)
                    {
                        materialtype = null;
                    }
                    _aMP_MaterialType_Id = value;
                }
            }
        }
        private int _aMP_MaterialType_Id;
    
        public virtual decimal AMP_Percentage
        {
            get;
            set;
        }
    
        public virtual bool AMP_IsActive
        {
            get;
            set;
        }
    
        public virtual int AMP_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AMP_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AMP_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool AMP_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual agentdetail agentdetail
        {
            get { return _agentdetail; }
            set
            {
                if (!ReferenceEquals(_agentdetail, value))
                {
                    var previousValue = _agentdetail;
                    _agentdetail = value;
                    Fixupagentdetail(previousValue);
                }
            }
        }
        private agentdetail _agentdetail;
    
        public virtual materialtype materialtype
        {
            get { return _materialtype; }
            set
            {
                if (!ReferenceEquals(_materialtype, value))
                {
                    var previousValue = _materialtype;
                    _materialtype = value;
                    Fixupmaterialtype(previousValue);
                }
            }
        }
        private materialtype _materialtype;

        #endregion
        #region Association Fixup
    
        private void Fixupagentdetail(agentdetail previousValue)
        {
            if (previousValue != null && previousValue.agentmaterialpercentages.Contains(this))
            {
                previousValue.agentmaterialpercentages.Remove(this);
            }
    
            if (agentdetail != null)
            {
                if (!agentdetail.agentmaterialpercentages.Contains(this))
                {
                    agentdetail.agentmaterialpercentages.Add(this);
                }
                if (AMP_Agent_Id != agentdetail.Agent_Id)
                {
                    AMP_Agent_Id = agentdetail.Agent_Id;
                }
            }
        }
    
        private void Fixupmaterialtype(materialtype previousValue)
        {
            if (previousValue != null && previousValue.agentmaterialpercentages.Contains(this))
            {
                previousValue.agentmaterialpercentages.Remove(this);
            }
    
            if (materialtype != null)
            {
                if (!materialtype.agentmaterialpercentages.Contains(this))
                {
                    materialtype.agentmaterialpercentages.Add(this);
                }
                if (AMP_MaterialType_Id != materialtype.MaterialType_Id)
                {
                    AMP_MaterialType_Id = materialtype.MaterialType_Id;
                }
            }
        }

        #endregion
    }
}
