//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class ameblock : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Blocks_Id
        {
            get;
            set;
        }
    
        public virtual string Blocks_Name
        {
            get;
            set;
        }
    
        public virtual int Blocks_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Blocks_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Blocks_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool Blocks_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<customer> customers
        {
            get
            {
                if (_customers == null)
                {
                    var newCollection = new FixupCollection<customer>();
                    newCollection.CollectionChanged += Fixupcustomers;
                    _customers = newCollection;
                }
                return _customers;
            }
            set
            {
                if (!ReferenceEquals(_customers, value))
                {
                    var previousValue = _customers as FixupCollection<customer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupcustomers;
                    }
                    _customers = value;
                    var newValue = value as FixupCollection<customer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupcustomers;
                    }
                }
            }
        }
        private ICollection<customer> _customers;

        #endregion
        #region Association Fixup
    
        private void Fixupcustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (customer item in e.NewItems)
                {
                    item.ameblock = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (customer item in e.OldItems)
                {
                    if (ReferenceEquals(item.ameblock, this))
                    {
                        item.ameblock = null;
                    }
                }
            }
        }

        #endregion
    }
}
