//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class authrepdocdetail : EntityBase
    {
        #region Primitive Properties
    
        public virtual int AuthRep_Doc_Id
        {
            get;
            set;
        }
    
        public virtual int AuthRep_Doc_AuthId
        {
            get { return _authRep_Doc_AuthId; }
            set
            {
                if (_authRep_Doc_AuthId != value)
                {
                    if (authrepdetail != null && authrepdetail.AuthRep_Id != value)
                    {
                        authrepdetail = null;
                    }
                    _authRep_Doc_AuthId = value;
                }
            }
        }
        private int _authRep_Doc_AuthId;
    
        public virtual int AuthRep_Doc_DocId
        {
            get { return _authRep_Doc_DocId; }
            set
            {
                if (_authRep_Doc_DocId != value)
                {
                    if (doctype != null && doctype.Doc_Id != value)
                    {
                        doctype = null;
                    }
                    _authRep_Doc_DocId = value;
                }
            }
        }
        private int _authRep_Doc_DocId;
    
        public virtual string AuthRep_Doc_DocNo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AuthRep_Doc_ExDate
        {
            get;
            set;
        }
    
        public virtual string AuthRep_Doc_FileName
        {
            get;
            set;
        }
    
        public virtual int AuthRep_Doc_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AuthRep_Doc_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AuthRep_Doc_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool AuthRep_Doc_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual authrepdetail authrepdetail
        {
            get { return _authrepdetail; }
            set
            {
                if (!ReferenceEquals(_authrepdetail, value))
                {
                    var previousValue = _authrepdetail;
                    _authrepdetail = value;
                    Fixupauthrepdetail(previousValue);
                }
            }
        }
        private authrepdetail _authrepdetail;
    
        public virtual doctype doctype
        {
            get { return _doctype; }
            set
            {
                if (!ReferenceEquals(_doctype, value))
                {
                    var previousValue = _doctype;
                    _doctype = value;
                    Fixupdoctype(previousValue);
                }
            }
        }
        private doctype _doctype;

        #endregion
        #region Association Fixup
    
        private void Fixupauthrepdetail(authrepdetail previousValue)
        {
            if (previousValue != null && previousValue.authrepdocdetails.Contains(this))
            {
                previousValue.authrepdocdetails.Remove(this);
            }
    
            if (authrepdetail != null)
            {
                if (!authrepdetail.authrepdocdetails.Contains(this))
                {
                    authrepdetail.authrepdocdetails.Add(this);
                }
                if (AuthRep_Doc_AuthId != authrepdetail.AuthRep_Id)
                {
                    AuthRep_Doc_AuthId = authrepdetail.AuthRep_Id;
                }
            }
        }
    
        private void Fixupdoctype(doctype previousValue)
        {
            if (previousValue != null && previousValue.authrepdocdetails.Contains(this))
            {
                previousValue.authrepdocdetails.Remove(this);
            }
    
            if (doctype != null)
            {
                if (!doctype.authrepdocdetails.Contains(this))
                {
                    doctype.authrepdocdetails.Add(this);
                }
                if (AuthRep_Doc_DocId != doctype.Doc_Id)
                {
                    AuthRep_Doc_DocId = doctype.Doc_Id;
                }
            }
        }

        #endregion
    }
}
