//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class authrepdocument : EntityBase
    {
        #region Primitive Properties
    
        public virtual int AuthRepDoc_Id
        {
            get;
            set;
        }
    
        public virtual int AuthRepDoc_Doc_Id
        {
            get;
            set;
        }
    
        public virtual byte[] AuthRepDoc_File
        {
            get;
            set;
        }
    
        public virtual int AuthRepDoc_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AuthRepDoc_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AuthRepDoc_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool AuthRepDoc_IsDeleted
        {
            get;
            set;
        }

        #endregion
    }
}
