//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class bank : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Bank_Id
        {
            get;
            set;
        }
    
        public virtual string Bank_Name
        {
            get;
            set;
        }
    
        public virtual string Bank_AccountNo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Bank_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Bank_LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Bank_IsDeleted
        {
            get;
            set;
        }

        #endregion
    }
}
