//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class batchtransfer : EntityBase
    {
        #region Primitive Properties
    
        public virtual int BT_ID
        {
            get;
            set;
        }
    
        public virtual int BT_CreatedBy
        {
            get;
            set;
        }
    
        public virtual System.DateTime BT_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> BT_ApprovedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BT_ApprovedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> BT_BankName
        {
            get;
            set;
        }
    
        public virtual string BT_BankBranch
        {
            get;
            set;
        }
    
        public virtual int BT_Status
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<paymenttransit> paymenttransits
        {
            get
            {
                if (_paymenttransits == null)
                {
                    var newCollection = new FixupCollection<paymenttransit>();
                    newCollection.CollectionChanged += Fixuppaymenttransits;
                    _paymenttransits = newCollection;
                }
                return _paymenttransits;
            }
            set
            {
                if (!ReferenceEquals(_paymenttransits, value))
                {
                    var previousValue = _paymenttransits as FixupCollection<paymenttransit>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuppaymenttransits;
                    }
                    _paymenttransits = value;
                    var newValue = value as FixupCollection<paymenttransit>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuppaymenttransits;
                    }
                }
            }
        }
        private ICollection<paymenttransit> _paymenttransits;

        #endregion
        #region Association Fixup
    
        private void Fixuppaymenttransits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (paymenttransit item in e.NewItems)
                {
                    item.batchtransfer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (paymenttransit item in e.OldItems)
                {
                    if (ReferenceEquals(item.batchtransfer, this))
                    {
                        item.batchtransfer = null;
                    }
                }
            }
        }

        #endregion
    }
}
