//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class bookingandsettlement : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Booking_Id
        {
            get;
            set;
        }
    
        public virtual int Booking_Cust_Id
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Booking_Date
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Booking_Month
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Booking_Year
        {
            get;
            set;
        }
    
        public virtual long Trips
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Quantity
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Account_Created_Date
        {
            get;
            set;
        }
    
        public virtual string TSL_Value
        {
            get;
            set;
        }

        #endregion
    }
}
