//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class businesstype : EntityBase
    {
        #region Primitive Properties
    
        public virtual int BusinessType_Id
        {
            get;
            set;
        }
    
        public virtual string BusinessType_Name
        {
            get;
            set;
        }
    
        public virtual int BusinessType_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BusinessType_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BusinessType_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool BusinessType_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<customer> customers
        {
            get
            {
                if (_customers == null)
                {
                    var newCollection = new FixupCollection<customer>();
                    newCollection.CollectionChanged += Fixupcustomers;
                    _customers = newCollection;
                }
                return _customers;
            }
            set
            {
                if (!ReferenceEquals(_customers, value))
                {
                    var previousValue = _customers as FixupCollection<customer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupcustomers;
                    }
                    _customers = value;
                    var newValue = value as FixupCollection<customer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupcustomers;
                    }
                }
            }
        }
        private ICollection<customer> _customers;
    
        public virtual ICollection<liftinglimit> liftinglimits
        {
            get
            {
                if (_liftinglimits == null)
                {
                    var newCollection = new FixupCollection<liftinglimit>();
                    newCollection.CollectionChanged += Fixupliftinglimits;
                    _liftinglimits = newCollection;
                }
                return _liftinglimits;
            }
            set
            {
                if (!ReferenceEquals(_liftinglimits, value))
                {
                    var previousValue = _liftinglimits as FixupCollection<liftinglimit>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupliftinglimits;
                    }
                    _liftinglimits = value;
                    var newValue = value as FixupCollection<liftinglimit>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupliftinglimits;
                    }
                }
            }
        }
        private ICollection<liftinglimit> _liftinglimits;
    
        public virtual ICollection<liftinglimit_history> liftinglimit_history
        {
            get
            {
                if (_liftinglimit_history == null)
                {
                    var newCollection = new FixupCollection<liftinglimit_history>();
                    newCollection.CollectionChanged += Fixupliftinglimit_history;
                    _liftinglimit_history = newCollection;
                }
                return _liftinglimit_history;
            }
            set
            {
                if (!ReferenceEquals(_liftinglimit_history, value))
                {
                    var previousValue = _liftinglimit_history as FixupCollection<liftinglimit_history>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupliftinglimit_history;
                    }
                    _liftinglimit_history = value;
                    var newValue = value as FixupCollection<liftinglimit_history>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupliftinglimit_history;
                    }
                }
            }
        }
        private ICollection<liftinglimit_history> _liftinglimit_history;

        #endregion
        #region Association Fixup
    
        private void Fixupcustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (customer item in e.NewItems)
                {
                    item.businesstype = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (customer item in e.OldItems)
                {
                    if (ReferenceEquals(item.businesstype, this))
                    {
                        item.businesstype = null;
                    }
                }
            }
        }
    
        private void Fixupliftinglimits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (liftinglimit item in e.NewItems)
                {
                    item.businesstype = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (liftinglimit item in e.OldItems)
                {
                    if (ReferenceEquals(item.businesstype, this))
                    {
                        item.businesstype = null;
                    }
                }
            }
        }
    
        private void Fixupliftinglimit_history(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (liftinglimit_history item in e.NewItems)
                {
                    item.businesstype = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (liftinglimit_history item in e.OldItems)
                {
                    if (ReferenceEquals(item.businesstype, this))
                    {
                        item.businesstype = null;
                    }
                }
            }
        }

        #endregion
    }
}
