//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class customer_history : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Cust_Id
        {
            get;
            set;
        }
    
        public virtual string Cust_Code
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Cust_AgentId
        {
            get;
            set;
        }
    
        public virtual string Cust_TradeName
        {
            get;
            set;
        }
    
        public virtual string Cust_FirmName
        {
            get;
            set;
        }
    
        public virtual string Cust_OwnerName
        {
            get;
            set;
        }
    
        public virtual string Cust_FathersName
        {
            get;
            set;
        }
    
        public virtual string Cust_RegisteredAddress
        {
            get;
            set;
        }
    
        public virtual string Cust_UnitAddress
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Cust_State
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Cust_District
        {
            get;
            set;
        }
    
        public virtual string Cust_Landmark
        {
            get;
            set;
        }
    
        public virtual int Cust_Pincode
        {
            get;
            set;
        }
    
        public virtual string Cust_MobileNo
        {
            get;
            set;
        }
    
        public virtual string Cust_PhoneNo
        {
            get;
            set;
        }
    
        public virtual int Cust_OwnershipStatus
        {
            get;
            set;
        }
    
        public virtual int Cust_BusinessType
        {
            get;
            set;
        }
    
        public virtual int Cust_SalesType
        {
            get;
            set;
        }
    
        public virtual bool Cust_RegCustType
        {
            get;
            set;
        }
    
        public virtual string Cust_PartnerPhoneNo
        {
            get;
            set;
        }
    
        public virtual int Cust_AMEBlockId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Cust_AMEVisitDate
        {
            get;
            set;
        }
    
        public virtual bool Cust_Status
        {
            get;
            set;
        }
    
        public virtual bool Cust_IsBlacklisted
        {
            get;
            set;
        }
    
        public virtual string Cust_BlacklistedBy
        {
            get;
            set;
        }
    
        public virtual string Cust_FolderName
        {
            get;
            set;
        }
    
        public virtual int Cust_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Cust_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Cust_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool Cust_IsDeleted
        {
            get;
            set;
        }

        #endregion
    }
}
