//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class custauthorizationdetail : EntityBase
    {
        #region Primitive Properties
    
        public virtual int CustAuth_Id
        {
            get;
            set;
        }
    
        public virtual int CustAuth_CustId
        {
            get { return _custAuth_CustId; }
            set
            {
                if (_custAuth_CustId != value)
                {
                    if (customer != null && customer.Cust_Id != value)
                    {
                        customer = null;
                    }
                    _custAuth_CustId = value;
                }
            }
        }
        private int _custAuth_CustId;
    
        public virtual Nullable<System.DateTime> CustAuth_Date
        {
            get;
            set;
        }
    
        public virtual byte[] CustAuth_File
        {
            get;
            set;
        }
    
        public virtual string CustAuth_FileName
        {
            get;
            set;
        }
    
        public virtual bool CustAuth_Status
        {
            get;
            set;
        }
    
        public virtual string CustAuth_Remarks
        {
            get;
            set;
        }
    
        public virtual int CustAuth_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CustAuth_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CustAuth_LastUpdateDate
        {
            get;
            set;
        }
    
        public virtual bool CustAuth_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual customer customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    Fixupcustomer(previousValue);
                }
            }
        }
        private customer _customer;

        #endregion
        #region Association Fixup
    
        private void Fixupcustomer(customer previousValue)
        {
            if (previousValue != null && previousValue.custauthorizationdetails.Contains(this))
            {
                previousValue.custauthorizationdetails.Remove(this);
            }
    
            if (customer != null)
            {
                if (!customer.custauthorizationdetails.Contains(this))
                {
                    customer.custauthorizationdetails.Add(this);
                }
                if (CustAuth_CustId != customer.Cust_Id)
                {
                    CustAuth_CustId = customer.Cust_Id;
                }
            }
        }

        #endregion
    }
}
