//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class customerdocumentsview : EntityBase
    {
        #region Primitive Properties
    
        public virtual int CustDoc_Id
        {
            get;
            set;
        }
    
        public virtual int CustDoc_Doc_Id
        {
            get;
            set;
        }
    
        public virtual int CustDoc_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CustDoc_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CustDoc_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool CustDoc_IsDeleted
        {
            get;
            set;
        }

        #endregion
    }
}
