//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class customerdetailsforcodealloc : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Cust_Id
        {
            get;
            set;
        }
    
        public virtual string Cust_Code
        {
            get;
            set;
        }
    
        public virtual string Cust_TradeName
        {
            get;
            set;
        }
    
        public virtual string Cust_OwnerName
        {
            get;
            set;
        }
    
        public virtual string Cust_FirmName
        {
            get;
            set;
        }
    
        public virtual string Cust_RegisteredAddress
        {
            get;
            set;
        }
    
        public virtual string Cust_UnitAddress
        {
            get;
            set;
        }
    
        public virtual int Cust_Pincode
        {
            get;
            set;
        }
    
        public virtual string state
        {
            get;
            set;
        }
    
        public virtual string district
        {
            get;
            set;
        }
    
        public virtual string businesstype
        {
            get;
            set;
        }
    
        public virtual string TIN
        {
            get;
            set;
        }
    
        public virtual string PAN
        {
            get;
            set;
        }
    
        public virtual Nullable<long> AnnualRequirement
        {
            get;
            set;
        }
    
        public virtual string Cust_MobileNo
        {
            get;
            set;
        }

        #endregion
    }
}
