//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class customerpartner : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Cust_Partner_ID
        {
            get;
            set;
        }
    
        public virtual int Cust_Partner_CustId
        {
            get { return _cust_Partner_CustId; }
            set
            {
                if (_cust_Partner_CustId != value)
                {
                    if (customer != null && customer.Cust_Id != value)
                    {
                        customer = null;
                    }
                    _cust_Partner_CustId = value;
                }
            }
        }
        private int _cust_Partner_CustId;
    
        public virtual string Cust_Partner_Name
        {
            get;
            set;
        }
    
        public virtual string Cust_Partner_FatherName
        {
            get;
            set;
        }
    
        public virtual bool Cust_Partner_IsBlacklisted
        {
            get;
            set;
        }
    
        public virtual string Cust_Partner_BlacklistedBy
        {
            get;
            set;
        }
    
        public virtual int Cust_Partner_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Cust_Partner_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Cust_Partner_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool Cust_Partner_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual customer customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    Fixupcustomer(previousValue);
                }
            }
        }
        private customer _customer;

        #endregion
        #region Association Fixup
    
        private void Fixupcustomer(customer previousValue)
        {
            if (previousValue != null && previousValue.customerpartners.Contains(this))
            {
                previousValue.customerpartners.Remove(this);
            }
    
            if (customer != null)
            {
                if (!customer.customerpartners.Contains(this))
                {
                    customer.customerpartners.Add(this);
                }
                if (Cust_Partner_CustId != customer.Cust_Id)
                {
                    Cust_Partner_CustId = customer.Cust_Id;
                }
            }
        }

        #endregion
    }
}
