//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class dcamaterialallocation : EntityBase
    {
        #region Primitive Properties
    
        public virtual int DCAMA_ID
        {
            get;
            set;
        }
    
        public virtual System.DateTime DCAMA_Date
        {
            get;
            set;
        }
    
        public virtual int DCAMA_Agent_Id
        {
            get { return _dCAMA_Agent_Id; }
            set
            {
                if (_dCAMA_Agent_Id != value)
                {
                    if (agentdetail != null && agentdetail.Agent_Id != value)
                    {
                        agentdetail = null;
                    }
                    _dCAMA_Agent_Id = value;
                }
            }
        }
        private int _dCAMA_Agent_Id;
    
        public virtual int DCAMA_MaterialType_Id
        {
            get { return _dCAMA_MaterialType_Id; }
            set
            {
                if (_dCAMA_MaterialType_Id != value)
                {
                    if (materialtype != null && materialtype.MaterialType_Id != value)
                    {
                        materialtype = null;
                    }
                    _dCAMA_MaterialType_Id = value;
                }
            }
        }
        private int _dCAMA_MaterialType_Id;
    
        public virtual decimal DCAMA_TodayPercentage
        {
            get;
            set;
        }
    
        public virtual int DCAMA_AllocatedQty
        {
            get;
            set;
        }
    
        public virtual int DCAMA_LastQty
        {
            get;
            set;
        }
    
        public virtual decimal DCAMA_CurrentPercentage
        {
            get;
            set;
        }
    
        public virtual decimal DCAMA_CurrentVariance
        {
            get;
            set;
        }
    
        public virtual decimal DCAMA_ActualPercentage
        {
            get;
            set;
        }
    
        public virtual decimal DCAMA_ActualVariance
        {
            get;
            set;
        }
    
        public virtual bool DCAMA_IsAgentActive
        {
            get;
            set;
        }
    
        public virtual int DCAMA_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DCAMA_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DCAMA_LastUpdatedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual agentdetail agentdetail
        {
            get { return _agentdetail; }
            set
            {
                if (!ReferenceEquals(_agentdetail, value))
                {
                    var previousValue = _agentdetail;
                    _agentdetail = value;
                    Fixupagentdetail(previousValue);
                }
            }
        }
        private agentdetail _agentdetail;
    
        public virtual materialtype materialtype
        {
            get { return _materialtype; }
            set
            {
                if (!ReferenceEquals(_materialtype, value))
                {
                    var previousValue = _materialtype;
                    _materialtype = value;
                    Fixupmaterialtype(previousValue);
                }
            }
        }
        private materialtype _materialtype;

        #endregion
        #region Association Fixup
    
        private void Fixupagentdetail(agentdetail previousValue)
        {
            if (previousValue != null && previousValue.dcamaterialallocations.Contains(this))
            {
                previousValue.dcamaterialallocations.Remove(this);
            }
    
            if (agentdetail != null)
            {
                if (!agentdetail.dcamaterialallocations.Contains(this))
                {
                    agentdetail.dcamaterialallocations.Add(this);
                }
                if (DCAMA_Agent_Id != agentdetail.Agent_Id)
                {
                    DCAMA_Agent_Id = agentdetail.Agent_Id;
                }
            }
        }
    
        private void Fixupmaterialtype(materialtype previousValue)
        {
            if (previousValue != null && previousValue.dcamaterialallocations.Contains(this))
            {
                previousValue.dcamaterialallocations.Remove(this);
            }
    
            if (materialtype != null)
            {
                if (!materialtype.dcamaterialallocations.Contains(this))
                {
                    materialtype.dcamaterialallocations.Add(this);
                }
                if (DCAMA_MaterialType_Id != materialtype.MaterialType_Id)
                {
                    DCAMA_MaterialType_Id = materialtype.MaterialType_Id;
                }
            }
        }

        #endregion
    }
}
