//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class dispatchreport : EntityBase
    {
        #region Primitive Properties
    
        public virtual int bookingid
        {
            get;
            set;
        }
    
        public virtual string LoadingAdvNo
        {
            get;
            set;
        }
    
        public virtual string TSLInvNo
        {
            get;
            set;
        }
    
        public virtual string TruckNo
        {
            get;
            set;
        }
    
        public virtual string CustCode
        {
            get;
            set;
        }
    
        public virtual string UnitName
        {
            get;
            set;
        }
    
        public virtual string District
        {
            get;
            set;
        }
    
        public virtual string QtyLiftedMts
        {
            get;
            set;
        }
    
        public virtual string TSLAmount
        {
            get;
            set;
        }
    
        public virtual string DCABillHandling
        {
            get;
            set;
        }
    
        public virtual string ServiceTax
        {
            get;
            set;
        }
    
        public virtual string ECess2
        {
            get;
            set;
        }
    
        public virtual string HECess1
        {
            get;
            set;
        }
    
        public virtual string AdvanceReceived
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Booking_Date
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Booking_Agent_Id
        {
            get;
            set;
        }

        #endregion
    }
}
