//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class form27cperiodtype : EntityBase
    {
        #region Primitive Properties
    
        public virtual int form27cPeriodType_Id
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ModifiedBy
        {
            get;
            set;
        }
    
        public virtual string PeriodType
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PeriodTypeId
        {
            get { return _periodTypeId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_periodTypeId != value)
                    {
                        if (periodtype1 != null && periodtype1.PeriodType_Id != value)
                        {
                            periodtype1 = null;
                        }
                        _periodTypeId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _periodTypeId;

        #endregion
        #region Navigation Properties
    
        public virtual periodtype periodtype1
        {
            get { return _periodtype1; }
            set
            {
                if (!ReferenceEquals(_periodtype1, value))
                {
                    var previousValue = _periodtype1;
                    _periodtype1 = value;
                    Fixupperiodtype1(previousValue);
                }
            }
        }
        private periodtype _periodtype1;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupperiodtype1(periodtype previousValue)
        {
            if (previousValue != null && previousValue.form27cperiodtype.Contains(this))
            {
                previousValue.form27cperiodtype.Remove(this);
            }
    
            if (periodtype1 != null)
            {
                if (!periodtype1.form27cperiodtype.Contains(this))
                {
                    periodtype1.form27cperiodtype.Add(this);
                }
                if (PeriodTypeId != periodtype1.PeriodType_Id)
                {
                    PeriodTypeId = periodtype1.PeriodType_Id;
                }
            }
            else if (!_settingFK)
            {
                PeriodTypeId = null;
            }
        }

        #endregion
    }
}
