//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class liftinginterval : EntityBase
    {
        #region Primitive Properties
    
        public virtual int liftinginterval_Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> liftinginterval_Interval
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> liftinginterval_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> liftinginterval_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> liftinginterval_LastUpdatedDate
        {
            get;
            set;
        }

        #endregion
    }
}
