//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class liftinglimit : EntityBase
    {
        #region Primitive Properties
    
        public virtual int LiftingLimit_ID
        {
            get;
            set;
        }
    
        public virtual int LiftingLimit_Limit
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LifitingLimit_Date
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> LiftingLimit_IsActive
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LiftingLimit_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LiftingLimit_LastUpdated
        {
            get;
            set;
        }
    
        public virtual int LiftingLimit_CreatedBy
        {
            get;
            set;
        }
    
        public virtual int LiftingLimit_Timeinterval
        {
            get;
            set;
        }
    
        public virtual int LiftingLimit_BusinessTypeID
        {
            get { return _liftingLimit_BusinessTypeID; }
            set
            {
                if (_liftingLimit_BusinessTypeID != value)
                {
                    if (businesstype != null && businesstype.BusinessType_Id != value)
                    {
                        businesstype = null;
                    }
                    _liftingLimit_BusinessTypeID = value;
                }
            }
        }
        private int _liftingLimit_BusinessTypeID;
    
        public virtual int Annual_LiftingLimit_Limit
        {
            get;
            set;
        }
    
        public virtual int LiftingLimit_TruckRegType_Id
        {
            get { return _liftingLimit_TruckRegType_Id; }
            set
            {
                if (_liftingLimit_TruckRegType_Id != value)
                {
                    if (truckregtype != null && truckregtype.TruckRegType_Id != value)
                    {
                        truckregtype = null;
                    }
                    _liftingLimit_TruckRegType_Id = value;
                }
            }
        }
        private int _liftingLimit_TruckRegType_Id;
    
        public virtual Nullable<int> LiftingLimit_IntervalId
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual businesstype businesstype
        {
            get { return _businesstype; }
            set
            {
                if (!ReferenceEquals(_businesstype, value))
                {
                    var previousValue = _businesstype;
                    _businesstype = value;
                    Fixupbusinesstype(previousValue);
                }
            }
        }
        private businesstype _businesstype;
    
        public virtual truckregtype truckregtype
        {
            get { return _truckregtype; }
            set
            {
                if (!ReferenceEquals(_truckregtype, value))
                {
                    var previousValue = _truckregtype;
                    _truckregtype = value;
                    Fixuptruckregtype(previousValue);
                }
            }
        }
        private truckregtype _truckregtype;

        #endregion
        #region Association Fixup
    
        private void Fixupbusinesstype(businesstype previousValue)
        {
            if (previousValue != null && previousValue.liftinglimits.Contains(this))
            {
                previousValue.liftinglimits.Remove(this);
            }
    
            if (businesstype != null)
            {
                if (!businesstype.liftinglimits.Contains(this))
                {
                    businesstype.liftinglimits.Add(this);
                }
                if (LiftingLimit_BusinessTypeID != businesstype.BusinessType_Id)
                {
                    LiftingLimit_BusinessTypeID = businesstype.BusinessType_Id;
                }
            }
        }
    
        private void Fixuptruckregtype(truckregtype previousValue)
        {
            if (previousValue != null && previousValue.liftinglimits.Contains(this))
            {
                previousValue.liftinglimits.Remove(this);
            }
    
            if (truckregtype != null)
            {
                if (!truckregtype.liftinglimits.Contains(this))
                {
                    truckregtype.liftinglimits.Add(this);
                }
                if (LiftingLimit_TruckRegType_Id != truckregtype.TruckRegType_Id)
                {
                    LiftingLimit_TruckRegType_Id = truckregtype.TruckRegType_Id;
                }
            }
        }

        #endregion
    }
}
