//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class loadingadivcerpt : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Booking_Id
        {
            get;
            set;
        }
    
        public virtual int Cust_Id
        {
            get;
            set;
        }
    
        public virtual string CustomerCode
        {
            get;
            set;
        }
    
        public virtual string CustomerName
        {
            get;
            set;
        }
    
        public virtual string NameofDistrict
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Booking_Date
        {
            get;
            set;
        }
    
        public virtual int AnnualQtyRequirement
        {
            get;
            set;
        }
    
        public virtual string QtyLimits
        {
            get;
            set;
        }

        #endregion
    }
}
