//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class my_ameblocks : EntityBase
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string dist_name
        {
            get;
            set;
        }
    
        public virtual string state_name
        {
            get;
            set;
        }
    
        public virtual string AME
        {
            get;
            set;
        }
    
        public virtual Nullable<int> dist_id
        {
            get;
            set;
        }

        #endregion
    }
}
