//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class pageinfo : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Page_Id
        {
            get;
            set;
        }
    
        public virtual string Page_Name
        {
            get;
            set;
        }
    
        public virtual string Page_NavigateURL
        {
            get;
            set;
        }
    
        public virtual int Page_Level
        {
            get;
            set;
        }
    
        public virtual int Page_ParentPageLevelId
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Page_IsActive
        {
            get;
            set;
        }
    
        public virtual int Page_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Page_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Page_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool Page_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<pagesinrole> pagesinroles
        {
            get
            {
                if (_pagesinroles == null)
                {
                    var newCollection = new FixupCollection<pagesinrole>();
                    newCollection.CollectionChanged += Fixuppagesinroles;
                    _pagesinroles = newCollection;
                }
                return _pagesinroles;
            }
            set
            {
                if (!ReferenceEquals(_pagesinroles, value))
                {
                    var previousValue = _pagesinroles as FixupCollection<pagesinrole>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuppagesinroles;
                    }
                    _pagesinroles = value;
                    var newValue = value as FixupCollection<pagesinrole>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuppagesinroles;
                    }
                }
            }
        }
        private ICollection<pagesinrole> _pagesinroles;

        #endregion
        #region Association Fixup
    
        private void Fixuppagesinroles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (pagesinrole item in e.NewItems)
                {
                    item.pageinfo = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (pagesinrole item in e.OldItems)
                {
                    if (ReferenceEquals(item.pageinfo, this))
                    {
                        item.pageinfo = null;
                    }
                }
            }
        }

        #endregion
    }
}
