//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class periodtype : EntityBase
    {
        #region Primitive Properties
    
        public virtual int PeriodType_Id
        {
            get;
            set;
        }
    
        public virtual string PeriodTypeName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CreatedBy
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<form27cperiodtype> form27cperiodtype
        {
            get
            {
                if (_form27cperiodtype == null)
                {
                    var newCollection = new FixupCollection<form27cperiodtype>();
                    newCollection.CollectionChanged += Fixupform27cperiodtype;
                    _form27cperiodtype = newCollection;
                }
                return _form27cperiodtype;
            }
            set
            {
                if (!ReferenceEquals(_form27cperiodtype, value))
                {
                    var previousValue = _form27cperiodtype as FixupCollection<form27cperiodtype>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupform27cperiodtype;
                    }
                    _form27cperiodtype = value;
                    var newValue = value as FixupCollection<form27cperiodtype>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupform27cperiodtype;
                    }
                }
            }
        }
        private ICollection<form27cperiodtype> _form27cperiodtype;

        #endregion
        #region Association Fixup
    
        private void Fixupform27cperiodtype(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (form27cperiodtype item in e.NewItems)
                {
                    item.periodtype1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (form27cperiodtype item in e.OldItems)
                {
                    if (ReferenceEquals(item.periodtype1, this))
                    {
                        item.periodtype1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
