//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class rejectionreason : EntityBase
    {
        #region Primitive Properties
    
        public virtual int RR_Id
        {
            get;
            set;
        }
    
        public virtual string RR_Name
        {
            get;
            set;
        }
    
        public virtual int RR_CreatedBy
        {
            get;
            set;
        }
    
        public virtual System.DateTime RR_LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> RR_IsDeleted
        {
            get;
            set;
        }

        #endregion
    }
}
