//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class settlementofaccount : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Account_Id
        {
            get;
            set;
        }
    
        public virtual int Account_Booking_Id
        {
            get { return _account_Booking_Id; }
            set
            {
                if (_account_Booking_Id != value)
                {
                    if (booking != null && booking.Booking_Id != value)
                    {
                        booking = null;
                    }
                    _account_Booking_Id = value;
                }
            }
        }
        private int _account_Booking_Id;
    
        public virtual decimal Account_Quantity
        {
            get;
            set;
        }
    
        public virtual decimal Account_AdvanceReceived
        {
            get;
            set;
        }
    
        public virtual string Account_CFormNo
        {
            get;
            set;
        }
    
        public virtual string Account_FormDNumber
        {
            get;
            set;
        }
    
        public virtual string Account_HGNumber
        {
            get;
            set;
        }
    
        public virtual string Account_InvoiceNumber
        {
            get;
            set;
        }
    
        public virtual string Account_GatePassNo
        {
            get;
            set;
        }
    
        public virtual string Account_RoadPermitNo
        {
            get;
            set;
        }
    
        public virtual decimal Account_TiscoRate
        {
            get;
            set;
        }
    
        public virtual decimal Account_HandlingRate
        {
            get;
            set;
        }
    
        public virtual decimal Account_HandlingServiceTax
        {
            get;
            set;
        }
    
        public virtual decimal Account_HandlingECess
        {
            get;
            set;
        }
    
        public virtual decimal Account_HandlingHECess
        {
            get;
            set;
        }
    
        public virtual decimal Account_TotalAmount
        {
            get;
            set;
        }
    
        public virtual decimal Account_Balance
        {
            get;
            set;
        }
    
        public virtual string Account_RateGroup
        {
            get;
            set;
        }
    
        public virtual int Account_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Account_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Account_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool Account_IsDeleted
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Account_Form27CId
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual booking booking
        {
            get { return _booking; }
            set
            {
                if (!ReferenceEquals(_booking, value))
                {
                    var previousValue = _booking;
                    _booking = value;
                    Fixupbooking(previousValue);
                }
            }
        }
        private booking _booking;

        #endregion
        #region Association Fixup
    
        private void Fixupbooking(booking previousValue)
        {
            if (previousValue != null && previousValue.settlementofaccounts.Contains(this))
            {
                previousValue.settlementofaccounts.Remove(this);
            }
    
            if (booking != null)
            {
                if (!booking.settlementofaccounts.Contains(this))
                {
                    booking.settlementofaccounts.Add(this);
                }
                if (Account_Booking_Id != booking.Booking_Id)
                {
                    Account_Booking_Id = booking.Booking_Id;
                }
            }
        }

        #endregion
    }
}
