//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class smsbookinglimit : EntityBase
    {
        #region Primitive Properties
    
        public virtual int SMSLimit_Id
        {
            get;
            set;
        }
    
        public virtual int SMSLimit_Limit
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SMSLimit_Date
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SMSLimit_IsActive
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SMSLimit_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SMSLimit_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual int SMSLimit_CreatedBy
        {
            get;
            set;
        }
    
        public virtual string SMSLimit_AuthorizedBy
        {
            get;
            set;
        }

        #endregion
    }
}
