//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class smsexecutivelist : EntityBase
    {
        #region Primitive Properties
    
        public virtual int SmsExecutiveList_Id
        {
            get;
            set;
        }
    
        public virtual string SmsExecutiveList_Name
        {
            get;
            set;
        }
    
        public virtual string SmsExecutiveList_PhoneNumber
        {
            get;
            set;
        }

        #endregion
    }
}
