//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class smspaymentregistration : EntityBase
    {
        #region Primitive Properties
    
        public virtual int SMSPay_Id
        {
            get;
            set;
        }
    
        public virtual int SMSPay_CustId
        {
            get { return _sMSPay_CustId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_sMSPay_CustId != value)
                    {
                        if (customer != null && customer.Cust_Id != value)
                        {
                            customer = null;
                        }
                        _sMSPay_CustId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _sMSPay_CustId;
    
        public virtual string SMSPay_CustCode
        {
            get;
            set;
        }
    
        public virtual decimal SMSPay_Amount
        {
            get;
            set;
        }
    
        public virtual System.DateTime SMSPay_Date
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SMSPay_Payment_Id
        {
            get { return _sMSPay_Payment_Id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_sMSPay_Payment_Id != value)
                    {
                        if (paymentcollection != null && paymentcollection.PC_Id != value)
                        {
                            paymentcollection = null;
                        }
                        _sMSPay_Payment_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _sMSPay_Payment_Id;
    
        public virtual Nullable<bool> SMSPay_Status
        {
            get;
            set;
        }
    
        public virtual string SMSPay_RejectionReason
        {
            get;
            set;
        }
    
        public virtual int SMSPay_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SMSPay_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SMSPay_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool SMSPay_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual customer customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    Fixupcustomer(previousValue);
                }
            }
        }
        private customer _customer;
    
        public virtual paymentcollection paymentcollection
        {
            get { return _paymentcollection; }
            set
            {
                if (!ReferenceEquals(_paymentcollection, value))
                {
                    var previousValue = _paymentcollection;
                    _paymentcollection = value;
                    Fixuppaymentcollection(previousValue);
                }
            }
        }
        private paymentcollection _paymentcollection;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupcustomer(customer previousValue)
        {
            if (previousValue != null && previousValue.smspaymentregistrations.Contains(this))
            {
                previousValue.smspaymentregistrations.Remove(this);
            }
    
            if (customer != null)
            {
                if (!customer.smspaymentregistrations.Contains(this))
                {
                    customer.smspaymentregistrations.Add(this);
                }
                if (SMSPay_CustId != customer.Cust_Id)
                {
                    SMSPay_CustId = customer.Cust_Id;
                }
            }
        }
    
        private void Fixuppaymentcollection(paymentcollection previousValue)
        {
            if (previousValue != null && previousValue.smspaymentregistrations.Contains(this))
            {
                previousValue.smspaymentregistrations.Remove(this);
            }
    
            if (paymentcollection != null)
            {
                if (!paymentcollection.smspaymentregistrations.Contains(this))
                {
                    paymentcollection.smspaymentregistrations.Add(this);
                }
                if (SMSPay_Payment_Id != paymentcollection.PC_Id)
                {
                    SMSPay_Payment_Id = paymentcollection.PC_Id;
                }
            }
            else if (!_settingFK)
            {
                SMSPay_Payment_Id = null;
            }
        }

        #endregion
    }
}
