//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class smsregistration : EntityBase
    {
        #region Primitive Properties
    
        public virtual int SMSReg_Id
        {
            get;
            set;
        }
    
        public virtual int SMSReg_CustId
        {
            get { return _sMSReg_CustId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_sMSReg_CustId != value)
                    {
                        if (customer != null && customer.Cust_Id != value)
                        {
                            customer = null;
                        }
                        _sMSReg_CustId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _sMSReg_CustId;
    
        public virtual string SMSReg_TruckNo
        {
            get;
            set;
        }
    
        public virtual string SMSReg_Msg
        {
            get;
            set;
        }
    
        public virtual System.DateTime SMSReg_Date
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SMSReg_Booking_Id
        {
            get { return _sMSReg_Booking_Id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_sMSReg_Booking_Id != value)
                    {
                        if (booking != null && booking.Booking_Id != value)
                        {
                            booking = null;
                        }
                        _sMSReg_Booking_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _sMSReg_Booking_Id;
    
        public virtual Nullable<bool> SMSReg_BookingStatus
        {
            get;
            set;
        }
    
        public virtual string SMSReg_RejectionReason
        {
            get;
            set;
        }
    
        public virtual int SMSReg_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SMSReg_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SMSReg_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool SMSReg_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual customer customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    Fixupcustomer(previousValue);
                }
            }
        }
        private customer _customer;
    
        public virtual booking booking
        {
            get { return _booking; }
            set
            {
                if (!ReferenceEquals(_booking, value))
                {
                    var previousValue = _booking;
                    _booking = value;
                    Fixupbooking(previousValue);
                }
            }
        }
        private booking _booking;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupcustomer(customer previousValue)
        {
            if (previousValue != null && previousValue.smsregistrations.Contains(this))
            {
                previousValue.smsregistrations.Remove(this);
            }
    
            if (customer != null)
            {
                if (!customer.smsregistrations.Contains(this))
                {
                    customer.smsregistrations.Add(this);
                }
                if (SMSReg_CustId != customer.Cust_Id)
                {
                    SMSReg_CustId = customer.Cust_Id;
                }
            }
        }
    
        private void Fixupbooking(booking previousValue)
        {
            if (previousValue != null && previousValue.smsregistrations.Contains(this))
            {
                previousValue.smsregistrations.Remove(this);
            }
    
            if (booking != null)
            {
                if (!booking.smsregistrations.Contains(this))
                {
                    booking.smsregistrations.Add(this);
                }
                if (SMSReg_Booking_Id != booking.Booking_Id)
                {
                    SMSReg_Booking_Id = booking.Booking_Id;
                }
            }
            else if (!_settingFK)
            {
                SMSReg_Booking_Id = null;
            }
        }

        #endregion
    }
}
