//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class truckdocument : EntityBase
    {
        #region Primitive Properties
    
        public virtual int TruckDoc_Id
        {
            get;
            set;
        }
    
        public virtual int TruckDoc_Doc_Id
        {
            get;
            set;
        }
    
        public virtual byte[] TruckDoc_File
        {
            get;
            set;
        }
    
        public virtual int TruckDoc_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TruckDoc_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TruckDoc_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool TruckDoc_IsDeleted
        {
            get;
            set;
        }

        #endregion
    }
}
