//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class truckdocdetail : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Truck_Doc_Id
        {
            get;
            set;
        }
    
        public virtual int Truck_Doc_TruckId
        {
            get { return _truck_Doc_TruckId; }
            set
            {
                if (_truck_Doc_TruckId != value)
                {
                    if (truckdetail != null && truckdetail.Truck_Id != value)
                    {
                        truckdetail = null;
                    }
                    _truck_Doc_TruckId = value;
                }
            }
        }
        private int _truck_Doc_TruckId;
    
        public virtual int Truck_Doc_DocId
        {
            get { return _truck_Doc_DocId; }
            set
            {
                if (_truck_Doc_DocId != value)
                {
                    if (doctype != null && doctype.Doc_Id != value)
                    {
                        doctype = null;
                    }
                    _truck_Doc_DocId = value;
                }
            }
        }
        private int _truck_Doc_DocId;
    
        public virtual string Truck_Doc_DocNo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Truck_Doc_ExDate
        {
            get;
            set;
        }
    
        public virtual string Truck_Doc_FileName
        {
            get;
            set;
        }
    
        public virtual int Truck_Doc_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Truck_Doc_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Truck_Doc_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool Truck_Doc_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual truckdetail truckdetail
        {
            get { return _truckdetail; }
            set
            {
                if (!ReferenceEquals(_truckdetail, value))
                {
                    var previousValue = _truckdetail;
                    _truckdetail = value;
                    Fixuptruckdetail(previousValue);
                }
            }
        }
        private truckdetail _truckdetail;
    
        public virtual doctype doctype
        {
            get { return _doctype; }
            set
            {
                if (!ReferenceEquals(_doctype, value))
                {
                    var previousValue = _doctype;
                    _doctype = value;
                    Fixupdoctype(previousValue);
                }
            }
        }
        private doctype _doctype;

        #endregion
        #region Association Fixup
    
        private void Fixuptruckdetail(truckdetail previousValue)
        {
            if (previousValue != null && previousValue.truckdocdetails.Contains(this))
            {
                previousValue.truckdocdetails.Remove(this);
            }
    
            if (truckdetail != null)
            {
                if (!truckdetail.truckdocdetails.Contains(this))
                {
                    truckdetail.truckdocdetails.Add(this);
                }
                if (Truck_Doc_TruckId != truckdetail.Truck_Id)
                {
                    Truck_Doc_TruckId = truckdetail.Truck_Id;
                }
            }
        }
    
        private void Fixupdoctype(doctype previousValue)
        {
            if (previousValue != null && previousValue.truckdocdetails.Contains(this))
            {
                previousValue.truckdocdetails.Remove(this);
            }
    
            if (doctype != null)
            {
                if (!doctype.truckdocdetails.Contains(this))
                {
                    doctype.truckdocdetails.Add(this);
                }
                if (Truck_Doc_DocId != doctype.Doc_Id)
                {
                    Truck_Doc_DocId = doctype.Doc_Id;
                }
            }
        }

        #endregion
    }
}
