//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class truckverification : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> type
        {
            get;
            set;
        }
    
        public virtual int Truck_Id
        {
            get;
            set;
        }
    
        public virtual string Truck_RegNo
        {
            get;
            set;
        }
    
        public virtual string Truck_OwnerName
        {
            get;
            set;
        }
    
        public virtual string Truck_DriverName
        {
            get;
            set;
        }
    
        public virtual string Truck_Address
        {
            get;
            set;
        }
    
        public virtual int Truck_State
        {
            get;
            set;
        }
    
        public virtual string Truck_MobileNo
        {
            get;
            set;
        }
    
        public virtual string Truck_PhoneNo
        {
            get;
            set;
        }
    
        public virtual int Truck_Make
        {
            get;
            set;
        }
    
        public virtual sbyte Truck_IsBlacklisted
        {
            get;
            set;
        }
    
        public virtual string Truck_BlacklistedBy
        {
            get;
            set;
        }
    
        public virtual int Truck_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Truck_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Truck_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual sbyte Truck_IsDeleted
        {
            get;
            set;
        }
    
        public virtual sbyte Truck_IsSuspended
        {
            get;
            set;
        }

        #endregion
    }
}
