//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TCESS.ESales.PersistenceLayer.Entity
{
    public partial class useragentmapping : EntityBase
    {
        #region Primitive Properties
    
        public virtual int UAM_Id
        {
            get;
            set;
        }
    
        public virtual int UAM_Agent_Id
        {
            get { return _uAM_Agent_Id; }
            set
            {
                if (_uAM_Agent_Id != value)
                {
                    if (agentdetail != null && agentdetail.Agent_Id != value)
                    {
                        agentdetail = null;
                    }
                    _uAM_Agent_Id = value;
                }
            }
        }
        private int _uAM_Agent_Id;
    
        public virtual int UAM_User_Id
        {
            get { return _uAM_User_Id; }
            set
            {
                if (_uAM_User_Id != value)
                {
                    if (my_aspnet_users != null && my_aspnet_users.id != value)
                    {
                        my_aspnet_users = null;
                    }
                    _uAM_User_Id = value;
                }
            }
        }
        private int _uAM_User_Id;
    
        public virtual int UAM_CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UAM_CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UAM_LastUpdatedDate
        {
            get;
            set;
        }
    
        public virtual bool UAM_IsDeleted
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual agentdetail agentdetail
        {
            get { return _agentdetail; }
            set
            {
                if (!ReferenceEquals(_agentdetail, value))
                {
                    var previousValue = _agentdetail;
                    _agentdetail = value;
                    Fixupagentdetail(previousValue);
                }
            }
        }
        private agentdetail _agentdetail;
    
        public virtual my_aspnet_users my_aspnet_users
        {
            get { return _my_aspnet_users; }
            set
            {
                if (!ReferenceEquals(_my_aspnet_users, value))
                {
                    var previousValue = _my_aspnet_users;
                    _my_aspnet_users = value;
                    Fixupmy_aspnet_users(previousValue);
                }
            }
        }
        private my_aspnet_users _my_aspnet_users;

        #endregion
        #region Association Fixup
    
        private void Fixupagentdetail(agentdetail previousValue)
        {
            if (previousValue != null && previousValue.useragentmappings.Contains(this))
            {
                previousValue.useragentmappings.Remove(this);
            }
    
            if (agentdetail != null)
            {
                if (!agentdetail.useragentmappings.Contains(this))
                {
                    agentdetail.useragentmappings.Add(this);
                }
                if (UAM_Agent_Id != agentdetail.Agent_Id)
                {
                    UAM_Agent_Id = agentdetail.Agent_Id;
                }
            }
        }
    
        private void Fixupmy_aspnet_users(my_aspnet_users previousValue)
        {
            if (previousValue != null && previousValue.useragentmappings.Contains(this))
            {
                previousValue.useragentmappings.Remove(this);
            }
    
            if (my_aspnet_users != null)
            {
                if (!my_aspnet_users.useragentmappings.Contains(this))
                {
                    my_aspnet_users.useragentmappings.Add(this);
                }
                if (UAM_User_Id != my_aspnet_users.id)
                {
                    UAM_User_Id = my_aspnet_users.id;
                }
            }
        }

        #endregion
    }
}
